### ISSUE TITLE
submodules not tracked

### ISSUE THREAD

**Issue by ThomasWalter** [sommerc/pyqt-stylesheets#1]
Hello, 

when I make a new clone of CellCognition, git will not clone the submodules (empty folder submodules/css, nothing else). Consequently, installation fails.

**Comment by sommerc** [comment]
I am afraid, we can't do much about this. That's the default behavior of git... [1]

Newer versions of git support "git clone <repo> --recursive". For older versions you have to use the git submodue init / update commands. Check out [1] to get more information.

[1] http://stackoverflow.com/questions/3796927/how-to-git-clone-including-submodules
